name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      publish: true

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          ref: publisher
          path: publisher
      - name: Get latest tag
        id: get-tag
        run: |
          git fetch --tags
          tag=$(git describe --tags)
          echo "${tag/v/version=}" >> $GITHUB_OUTPUT
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/download-artifact@v4
        id: get-artifacts
        with:
          path: publisher/temp/
      - name: Update manifest
        run: |
          python publisher/update_manifest.py
      - name: Push to GitHub
        run: |
          pushd publisher
          git add -A
          git -c user.name=GitHub -c user.email=noreply@github.com commit -m "${{ steps.get-tag.outputs.version }}"
          git push
          popd
