name: Build on push

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get latest tag
        id: get-tag
        run: |
          $(git describe --tags) -Replace '^v', 'version=' >> $env:GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          ref: publisher
          path: publisher
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build and pack package
        env:
          XZ_VERSION: ${{ steps.get-tag.outputs.version }}
        run: |
          Move-Item -Path "Jellyfin.Plugin.Douban/Jellyfin.Plugin.Douban.csproj" -Destination "Jellyfin.Plugin.Douban/Jellyfin.Plugin.Douban.csproj.bak"
          Get-Content -Path "Jellyfin.Plugin.Douban/Jellyfin.Plugin.Douban.csproj.bak" -Encoding UTF8 | ForEach-Object { $_ -Replace '<((?:Assembly|File)?Version)>[\d\.]+</\1>', "<`$1>$env:XZ_VERSION</`$1>" } | Out-File -FilePath "Jellyfin.Plugin.Douban/Jellyfin.Plugin.Douban.csproj" -Encoding UTF8
          dotnet publish "Jellyfin.Plugin.Douban/Jellyfin.Plugin.Douban.csproj" -c "Release" -o "./publisher"
          Remove-Item -Path "Jellyfin.Plugin.Douban/Jellyfin.Plugin.Douban.csproj"
          Move-Item -Path "Jellyfin.Plugin.Douban/Jellyfin.Plugin.Douban.csproj.bak" -Destination "Jellyfin.Plugin.Douban/Jellyfin.Plugin.Douban.csproj"
          Compress-Archive -Path publisher/Jellyfin.Plugin.Douban.dll,publisher/AnitomySharp.dll,publisher/HtmlAgilityPack.dll,publisher/HtmlAgilityPack.CssSelectors.dll,publisher/*.pdb -DestinationPath "publisher/dist/Jellyfin.Plugin.Douban.$env:XZ_VERSION.0.zip" -Force
          python publisher/update_manifest.py
      - name: Push to GitHub
        run: |
          Push-Location publisher
          git add -A
          git -c user.name=GitHub -c user.email=noreply@github.com commit -m "${{ steps.get-tag.outputs.version }}"
          git push
          Pop-Location
